language: go

go:
- tip

env:
  global:
  - secure: G8FU1aC0m8V+2BwtTXyRywcMXao8uU9s3pIx/MedZG1xt3xjQ+zuw9v1PHW4pCuyiuiqkBX6qZKNlDG2eunb5VZtz8+t8Jfku384H3NQLnR9QTOTQC1a04OaYjwgdWYQth5lrIDQyryingW6L1RJEXO4lJkF7nNTXWakvdfzR69bJVbP/o8kTDuqwqsdSn/u7A3ZLuWm3rMMjymfTJngFkj5yJw9uFjZ73ts+Kwrabxrz2M3mPG5iSA7VqG9dMKk43fQqH/VQhvxtynyLW/7HaY0MqYmyRIbrSgPlg4pSn1W7mWQOndt3neE9p7O50Q8I7adyN/CETKuTzIZUKIhbUilwk3NxgD7tKYnAG9U9Nn+oXypPV5Pl8x11YOSrSqFDluwiTYJBxUNX8RqQ6KTcBWI6Wb7uZ3eWCJwRh79P56CvAGEXOh+/fjn6J21nwe3VdaUD8YB7N6AUOkt/y424YXRTCHYoRUWARRAScxrgLtD4NO2ADK9STZ+9iT+KRj3YZeNd3QNw3v84FupK6Mzsqafy4XOTG8pQ+KuglXu05QsyrdLxPX/EIkybpewPU3aECkk9MEacbYuwoUeeIdBrKH1/Hr2GH4APqt367+OkaAn3EDBx57j9vx/f0ukv6jKOjG+Qmq+f3kxOTsPK6+O2x3qLIbLTttmgTpho9V65Lw=

install:
  - go get github.com/golang/freetype/raster
  - go get github.com/jonas-p/go-shp

before_script:
  - git config --global user.email "bender.rodriges@gmail.com"
  - git config --global user.name "Travis CI"
  - git config --global push.default simple

script:
  - curl -O http://efele.net/maps/tz/world/tz_world.zip
  - unzip tz_world.zip
  - go test --tags=latlong_gen --generate -v
  - rm -rf tz_world.zip world/

after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add -A
  - git commit -m "Daily Travis CI build"
  - git push