language: go

go:
  - tip
  
install:
  - go get github.com/golang/freetype/raster
  - go get github.com/jonas-p/go-shp
  
script:
  - curl http://efele.net/maps/tz/world/tz_world.zip
  - unzip tz_world.zip
  - make